hmcts/sscs-ccd-definitions

- benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
- benefit/data/sheets/CaseEvent/CaseEvent.json
- benefit/data/sheets/CaseEventToFields/CaseEventToFields-z-audiovideo-nonprod.json
- benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
- benefit/data/sheets/CaseField/CaseField.json
- benefit/data/sheets/EventToComplexTypes/EventToComplexTypes.json
https://tools.hmcts.net/jira/browse/SSCS-9449
> SSCS-9449 Remove AV playback workaround event and fields

- sonar-project.properties
> Exclude test directory

- .gitignore
- charts/sscs-ccd-definitions/Chart.yaml
- package.json
> Remove extra dependencies

- benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
- benefit/data/sheets/FixedLists/FixedLists-hearing-recording-nonprod.json
https://tools.hmcts.net/jira/browse/SSCS-9244
> SSCS-9244 Issue direction refuse hearing recording

- Jenkinsfile_CNP
Run the functional test in AAT
> run the functional test in AAT

- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
- benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
- benefit/data/sheets/CaseField/CaseField.json
- benefit/data/sheets/ComplexTypes/ComplexTypes.json
- benefit/data/sheets/FixedLists/FixedLists-postponement-request-nonprod.json
Reverts hmcts/sscs-ccd-definitions#733
> Revert "Sscs 9433 postponement req"

- benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
- benefit/data/sheets/CaseEvent/CaseEvent.json
- benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
- benefit/data/sheets/CaseField/CaseField.json
- benefit/data/sheets/FixedLists/FixedLists.json
https://tools.hmcts.net/jira/browse/SSCS-9438
Action Postponement Request Event - Send to Judge
```
[ ] Yes
[ x] No
```
> SSCS-9438-Merged master in

- benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields-postponements-nonprod.json
https://tools.hmcts.net/jira/browse/SSCS-9442
> Sscs 9442 unprocessed recording workbasket filter

- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
- benefit/data/sheets/CaseField/CaseField.json
- benefit/data/sheets/ComplexTypes/ComplexTypes.json
https://tools.hmcts.net/jira/browse/SSCS-9601
> SSCS-9601 Other parties

- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
- benefit/data/sheets/CaseField/CaseField.json
https://tools.hmcts.net/jira/browse/SSCS-9601
> SSCS-9601 Child maintenance number

- azure-pipelines.yml
> fix azure pipe line

- Jenkinsfile_CNP
> turn off high level data setup step in jenkins pipeline

- benefit/data/sheets/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/SSCS-9618
> SSCS-9618 Child Support hide generate pdf event

- benefit/data/sheets/ComplexTypes/ComplexTypes-audiovideo-nonprod.json
- benefit/data/sheets/FixedLists/FixedLists-audiovideo-nonprod.json
https://tools.hmcts.net/jira/browse/SSCS-9675
> SSCS-9675 Remove shouldBundleIncludeDocLink from av objects

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/SSCS-9626
added preview tag
```
[ ] Yes
[x] No
```
> sscs 9627 added a preview tag

- Jenkinsfile_CNP
SSCS-9626- run preview tag in aat
> SSCS-9626- run preview tag in aat

- package.json
SSCS-9626 - Run preview tag in AAT
> SSCS-9626 - Run preview tag in AAT

- bin/after-data-setup-step.sh
SSCS-9626 - Chown the file recursively to be able to move and delete if needed
> SSCS-9626 - Chown the file recursively to be able to move and delete if needed

- bin/after-data-setup-step.sh
> SSCS-9626 - Remove chown

- bin/after-data-setup-step.sh
SSCS-9626 - Remove after data setup script
...because I have no idea why it's needed.
> SSCS-9626 - Remove after data setup script

- bin/after-data-setup-step.sh
- bin/before-data-setup-step.sh
- package.json
SSCS-9626 - run docker with user
> SSCS-9626 - run docker with user

- bin/before-data-setup-step.sh
SSCS-9626 - Use latest AAT image for prod ccd definition file
> SSCS-9626 - Use latest AAT image for prod ccd definition file

- bin/before-data-setup-step.sh
SSCS-9626 - use latest prod image for prod
> SSCS-9626 - use latest prod image for prod

- bin/before-data-setup-step.sh
- package.json
SSCS-9626 - run high level data setup in AAT
> SSCS-9626 - run high level data setup in AAT

- package.json
- src/test/java/benefit/HighLevelDataSetupApp.java
SSCS-9626 - Enable functional tests, remove skip prod flag
> SSCS-9626 - Enable functional tests, remove skip prod flag

- Jenkinsfile_CNP
SSCS-9626 - Sync other branches
> SSCS-9626 - Sync other branches

- bin/before-data-setup-step.sh
SSCS-9626 - get image for demo, perftest and ithc
> SSCS-9626 - get image for demo, perftest and ithc

- benefit/data/sheets/CaseTypeTab/CaseTypeTab.json
https://tools.hmcts.net/jira/browse/SSCS-9623
> Sscs 9623 other party tab

- README.md
https://tools.hmcts.net/jira/browse/SSCS-9719
```
[ ] Yes
[ x] No
```
> SSCS-9719: Readme updated for sscs-common change

- bin/before-data-setup-step.sh
- package.json
> double brackets

- benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
https://tools.hmcts.net/jira/browse/SSCS-9897
remove other parties from event
```
[ ] Yes
[x] No
```
> sscs 9897 removed other parties from update to case data

- benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
https://tools.hmcts.net/jira/browse/SSCS-9744
```
[ ] Yes
[X ] No
```
> SSCS-9744 ExUI – Allow users to filter by DWP response due date

- benefit/data/sheets/WorkBasketInputFields/WorkBasketInputFields.json
Reverts hmcts/sscs-ccd-definitions#872
> Revert "SSCS-9744 ExUI – Allow users to filter by DWP response due date"

- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
- benefit/data/sheets/CaseField/CaseField.json
- benefit/data/sheets/CaseTypeTab/CaseTypeTab-nonprod.json
https://tools.hmcts.net/jira/browse/SSCS-9882
caseName field
```
[ ] Yes
[x] No
```
> sscs 9882 added caseName field

- package.json
- yarn.lock
Update dependency
```
[ ] Yes
[ ] No
```
> upgrade dependency

- bulkscan/data/sheets/CaseType.json
Update script for bulk scan case types
```
[ ] Yes
[X] No
```
> Update Case Types

- charts/sscs-ccd-definitions/Chart.yaml
https://tools.hmcts.net/jira/browse/SSCS-10236
```
[ ] Yes
[X] No
```
> SSCS-10236 updating helm chart version

- package.json
> SSCS-10222 Bump minimist.

- benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-sandl-nonprod.json
https://tools.hmcts.net/jira/browse/SSCS-10559
- adding superuser permissions to run the event + update case field
```
[ ] Yes
[x] No
```
> Feat/SSCS-10559: Granting superuser permissions for overrideduration

- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/SSCS-10242
```
[ ] Yes
[x] No
```
>  SSCS-10242 Hearing Date Filter Add Permissions

- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField.json
- benefit/data/sheets/CaseField/CaseField.json
- benefit/data/sheets/CaseTypeTab/CaseTypeTab-nonprod.json
https://tools.hmcts.net/jira/browse/SSCS-10334
Update field to have capital
```
[ ] Yes
[ ] No
```
> sscs 10334 added the correct field

- package.json
- yarn.lock
> SSCS-10334 Rollback healthcheck and properties volume bumps.

- bin/before-data-setup-step.sh
- charts/sscs-ccd-definitions/Chart.yaml
sscsBaseChartUpdate-nodeJs245
```
[ ] Yes
[ ] No
```
> sscsBaseChartUpdate-Java401

- bin/create-xlsx.sh
> SSCS-10315 Remove interactive docker prompt.

- benefit/data/sheets/FixedLists/FixedList-sandl-nonprod.json
- benefit/data/sheets/FixedLists/FixedLists.json
> CAM Release Pipeline failure

- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-sandl-nonprod.json
> SSCS-10167 fix

- .github/renovate.json
- renovate.json
> Add Renovate Bot

- bin/before-data-setup-step.sh
> Previewfunctional test fixes

- build.gradle
- src/test/java/benefit/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/SSCS-11086
```
[x] Yes
[ ] No
```
> SSCS-11086 Fix CCD pipeline to fail on incorrect upload

- benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
- benefit/data/sheets/FixedLists/FixedLists.json
https://tools.hmcts.net/jira/browse/SSCS-10562
Change one of FTA office from "Child Support" to "Child Support Agency"
```
[ ] Yes
[X] No
```
> SSCS-10562 update Child Support to Child Support Agency

- benefit/data/sheets/FixedLists/FixedLists.json
- package.json
- yarn.lock
> SSCS-11276 - Update bexleyheaths venue entry EPIMS ID

- bin/before-data-setup-step.sh
- bin/create-xlsx.sh
> SSCS-11480 : Swapped to new bundling service demo url

- charts/sscs-ccd-definitions/Chart.yaml
> SSCS-11493 : Updated nodejs helm version from 2.4.11 to 2.4.14

- bin/before-data-setup-step.sh
- package.json
Pipeline fixture
```
[ ] Yes
[x] No
```
> Pipeline fixture

- e2e-tests/config/default.json
Pipeline fixture
```
[ ] Yes
[x] No
```
> Increase API callout time

- docker/importer.Dockerfile
- docker/xlsx2json.Dockerfile
> definition processort updated to latest

- docker/importer.Dockerfile
> importer Dockerfile fix

- benefit/data/sheets/CaseEvent/CaseEvent.json
- benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
https://tools.hmcts.net/jira/browse/SSCS-11107
Create Task "Review FTA Response" for CTSC Administrator
```
[ ] Yes
[X] No
```
> SSCS-11107 Review FTA Response

- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-WA-nonprod.json
- benefit/data/sheets/CaseEvent/CaseEvent.json
- benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA-nonprod.json
- benefit/data/sheets/CaseField/CaseField-WA-nonprod.json
https://tools.hmcts.net/jira/browse/SSCS-11873
Added field _daysToHearing_
```
[ ] Yes
[x] No
```
> Added field and published events for SSCS-11873

- benefit/data/sheets/CaseEvent/CaseEvent.json
- benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA-nonprod.json
- benefit/data/sheets/CaseEventToFields/CaseEventToFields-dwpUploadResponse.json
https://tools.hmcts.net/jira/browse/SSCS-10048
Published required events and fields.
```
[ ] Yes
[X] No
```
> SSCS-10048 Create "Review PHE Request" Task for Judge

- benefit/data/sheets/CaseEventToFields/CaseEventToFields-WA-nonprod.json
https://tools.hmcts.net/jira/browse/SSCS-11994
Make field directionTypeDl optional 
```
[ ] Yes
[x] No
```
> SSCS-11994 Update directionDueToday event

- benefit/data/sheets/AuthorisationCaseEvent/AuthorisationCaseEvent.json
> Sscs 11984

- benefit/data/sheets/CaseEventToFields/CaseEventToFields.json
https://tools.hmcts.net/jira/browse/SSCS-12100
fixed postopementDetails being null in about to submit
> fixed postopementDetails being null in about to submit

- bin/before-data-setup-step.sh
- bin/create-xlsx.sh
- bin/template-urls.sh
- bin/upload-ccd-definition-to-env.sh
https://tools.hmcts.net/jira/browse/SSCSSI-156 
- Unused in scripts, References previously removed in https://github.com/hmcts/sscs-ccd-definitions/pull/1529
> SSCSSI-156 Remove references to unused sscs orchestrator

- .gitignore
- functional-test/config/playwright.config.ts
- functional-test/lib/webActions.ts
- functional-test/pages/addNotePage.ts
- functional-test/pages/loginPage.ts
- package.json
https://tools.hmcts.net/jira/browse/SSCSSI-178
> Si 178 report creation

- Jenkinsfile_CNP
- functional-test/common/web.action.ts
- functional-test/config/config.ts
- functional-test/e2e/add-note.spec.ts
- functional-test/e2e/confirm-case-lapsed.spec.ts
- functional-test/fixtures/steps/confirm.case.lapsed.ts
- functional-test/fixtures/steps/note.ts
- functional-test/lib/steps.factory.ts
- functional-test/pages/add.note.ts
- functional-test/pages/common/event.name.event.description.ts
- functional-test/pages/common/homePage.ts
- functional-test/pages/common/loginPage.ts
- functional-test/pages/content/event.name.event.description_en.json
- functional-test/pages/tabs/history.ts
- functional-test/playwright.config.ts
- functional-test/utils/DateUtilsComponent.ts
- functional-test/utils/StringUtilsComponent.ts
- package.json
https://tools.hmcts.net/jira/browse/SSCSSI-177
> Code modified with CI Config

- benefit/data/sheets/AuthorisationCaseField/AuthorisationCaseField-GS.json
https://tools.hmcts.net/jira/browse/SSCS-12498
Given GS_profile profile read access to SearchCriteria fields
> SSCS-12498 Fix global search

- Jenkinsfile_CNP
- functional-test/api/client/sscs/appeal.event.ts
- functional-test/api/client/sscs/factory/appeal.update.factory.ts
- functional-test/common/web.action.ts
- functional-test/config/config.ts
- functional-test/e2e/add-note.spec.ts
- functional-test/e2e/case-dormant.spec.ts
- functional-test/e2e/confirm-case-lapsed.spec.ts
- functional-test/e2e/evidence-reminder.spec.ts
- functional-test/e2e/listing-error.spec.ts
- functional-test/e2e/send-to-admin.spec.ts
- functional-test/fixtures/steps/base.ts
- functional-test/fixtures/steps/confirm.case.lapsed.ts
- functional-test/fixtures/steps/evidence.reminder.ts
- functional-test/fixtures/steps/listing.error.ts
- functional-test/fixtures/steps/note.ts
- functional-test/fixtures/steps/send.to.admin.ts
- functional-test/fixtures/steps/upload.response.ts
- functional-test/pages/common/homePage.ts
- functional-test/pages/common/loginPage.ts
> refactor: adding the hook methods to the tests.

- functional-test/config/config.ts
- functional-test/e2e/upload-response.spec.ts
- functional-test/fixtures/steps/base.ts
- functional-test/fixtures/steps/upload.response.ts
- functional-test/pages/common/loginPage.ts
> Fix upload response test

- functional-test/common/web.action.ts
- functional-test/e2e/add-note.spec.ts
- functional-test/e2e/send-to-judge.spec.ts
- functional-test/e2e/upload-response.spec.ts
- functional-test/fixtures/steps/associate-case.ts
- functional-test/fixtures/steps/base.ts
- functional-test/fixtures/steps/confirm.case.lapsed.ts
- functional-test/fixtures/steps/evidence.reminder.ts
- functional-test/fixtures/steps/listing.error.ts
- functional-test/fixtures/steps/note.ts
- functional-test/fixtures/steps/send.to.admin.ts
- functional-test/fixtures/steps/send.to.judge.ts
- functional-test/fixtures/steps/upload.response.ts
- functional-test/pages/common/homePage.ts
- functional-test/pages/common/loginPage.ts
- functional-test/pages/tabs/appealDetails.ts
- functional-test/pages/upload.response.page.ts
> Refactor login cookies

- functional-test/e2e/send-to-fta.spec.ts
- functional-test/fixtures/steps/base.ts
- functional-test/fixtures/steps/send.to.fta.ts
- functional-test/lib/steps.factory.ts
https://tools.hmcts.net/jira/browse/SSCSSI-189
> SSCSSI-189: Add test for "Send to With FTA" event

- functional-test/e2e/urgent-hearing.spec.ts
- functional-test/fixtures/steps/urgent.hearing.ts
- functional-test/pages/action.further.evidence.page.ts
- functional-test/pages/content/action.further.evidence_en.json
https://tools.hmcts.net/jira/browse/SSCSSI-186
> add file upload error tests

- functional-test/api/client/sscs/appeal.event.ts
- functional-test/common/web.action.ts
- functional-test/e2e/add-note.spec.ts
- functional-test/e2e/appeal-withdrawn.spec.ts
- functional-test/e2e/death-of-an-appellant.spec.ts
- functional-test/e2e/send-to-fta.spec.ts
- functional-test/e2e/urgent-hearing.spec.ts
- functional-test/fixtures/steps/base.ts
- functional-test/fixtures/steps/death.of.an.appelant.ts
- functional-test/fixtures/steps/send.to.fta.ts
- functional-test/lib/steps.factory.ts
- functional-test/pages/content/death.of.an.appellant_en.json
- functional-test/pages/death.of.appelant.ts
- functional-test/playwright.config.ts
> feat: add the death to appellant tests

- functional-test/e2e/urgent-hearing.spec.ts
- functional-test/fixtures/steps/base.ts
- functional-test/fixtures/steps/reinstatement.ts
- functional-test/fixtures/steps/urgent.hearing.ts
- functional-test/pages/content/allocate.role_en.json
- functional-test/pages/content/review.urgent.hearing.request.task_en.json
- functional-test/pages/content/send.case.to.tcw_en.json
- functional-test/pages/send.case.to.tcw.page.ts
- functional-test/pages/tabs/roles.and.access.ts
https://tools.hmcts.net/jira/browse/SSCSSI-280
This PR adds work allocation tests for Review Urgent Hearing Request - Judge task. As AAT and Demo are not available for work allocation tests at the moment, tests are run locally against preview environment(https://xui-sscs-tribunals-api-pr-3855.preview.platform.hmcts.net) and the tests passed.
> [SSCSSI-280]: Add Review Urgent Hearing Request - Judge work allocation task tests

- functional-test/e2e/search-filter.spec.ts
- functional-test/e2e/update-not-listable.spec.ts
- functional-test/fixtures/steps/base.ts
- functional-test/fixtures/steps/search.filter.ts
- functional-test/fixtures/steps/update.not.listable.ts
- functional-test/fixtures/steps/update.subscription.ts
- functional-test/lib/steps.factory.ts
- functional-test/pages/common/homePage.ts
- functional-test/pages/not.listable.page.ts
- functional-test/pages/search.filter.page.ts
- functional-test/pages/update.not.listable.page.ts
https://tools.hmcts.net/jira/browse/SSCSSI-203
Migrating 'search filter' scenario to playwright from the 'sscs-ccd-e2e-tests' repo
> SSCSSI-203 search filter scenario

- Jenkinsfile_CNP
- functional-test/config/config.ts
- functional-test/e2e/request-time-extension.spec.ts
- functional-test/fixtures/steps/request.time.extension.ts
- functional-test/pages/content/issue.direction_en.json
- functional-test/pages/content/review.fta.time.extension.request.task_en.json
- functional-test/pages/tabs/tasks.ts
https://tools.hmcts.net/jira/browse/SSCSSI-301
This PR adds ReviewFTA Time Extension Request - TCW work allocation task tests. Tests is successfully running locally against aat environment.
- [x ] README and other documentation has been updated / added (if needed)
- [ x] Does this PR introduce a breaking change
> Sscssi 301 review time extenstion request

- functional-test/e2e/enhanced-confidentiality.spec.ts
- functional-test/fixtures/steps/base.ts
- functional-test/fixtures/steps/create.bundle.ts
- functional-test/fixtures/steps/enhanced.confidentiality.ts
- functional-test/fixtures/steps/upload.response.ts
- functional-test/lib/steps.factory.ts
- functional-test/pages/action.further.evidence.page.ts
- functional-test/pages/content/action.further.evidence_en.json
- functional-test/pages/content/create.a.bundle_en.json
- functional-test/pages/content/review.confidentiality_en.json
- functional-test/pages/content/upload.response_en.json
- functional-test/pages/review.confidentiality.page.ts
- functional-test/pages/tabs/bundles.ts
- functional-test/pages/tabs/summary.ts
- functional-test/pages/upload.response.page.ts
- functional-test/playwright.config.ts
https://tools.hmcts.net/jira/browse/SSCSSI-185
> Enhanced confidentiality tests

- functional-test/e2e/referred-to-interloc-judge-task.spec.ts
- functional-test/e2e/referred-to-interloc.spec.ts
- functional-test/fixtures/steps/referred.to.interloc.judge.task.ts
- functional-test/fixtures/steps/send.to.interloc.ts
- functional-test/lib/steps.factory.ts
- functional-test/pages/content/referred.to.interloc.judge.task_en.json
- functional-test/pages/content/send.to.interloc_en.json
https://tools.hmcts.net/jira/browse/SSCSSI-275
This PR adds Referred to Interloc - Judge work allocation task tests. Tests is successfully running locally against preview environment.
> Sscssi 275 referred by interloc judge

- functional-test/e2e/referred-by-tcw-judge-task.spec.ts
- functional-test/fixtures/steps/referred.by.tcw.judge.task.ts
- functional-test/fixtures/steps/send.to.judge.ts
- functional-test/lib/steps.factory.ts
- functional-test/pages/content/referred.by.tcw.judge.task_en.json
- functional-test/pages/content/send.to.judge_en.json
- functional-test/pages/send.to.judge.page.ts
https://tools.hmcts.net/jira/browse/SSCSSI-282
This PR adds Referred by TCW - Judge work allocation task tests. Tests is successfully running locally against preview environment.
> Sscssi 282 add referred by TCW judge

- functional-test/e2e/abate-fta.not.provided.appointee,details.judge.task.spec.ts
- functional-test/e2e/abate-fta.not.provided.appointee.details.spec.ts
- functional-test/fixtures/steps/fta.not.provided.appointee.details.judge.task.ts
- functional-test/fixtures/steps/update.not.listable.ts
- functional-test/lib/steps.factory.ts
- functional-test/pages/content/review.fta.not.provided.appointee.details.judge.task_en.json
https://tools.hmcts.net/jira/browse/SSCSSI-276
This PR adds Abate FTA not provided appointee details  - Judge work allocation task tests. Tests is successfully running locally against preview environment.
> Sscssi 276 add abate Judge

- package.json
- yarn.lock
Add micromatch v 4.0.8 to resolutions
> SSCSCI - add micromatch to cve's

- functional-test/api/client/sscs/factory/appeal.type.factory.ts
- functional-test/api/data/payload/create-appeal/pip_sya_welsh.json
- functional-test/e2e/api-test-client.spec.ts
- functional-test/e2e/urgent-hearing.spec.ts
- functional-test/fixtures/steps/urgent.hearing.ts
- functional-test/pages/tabs/appealDetails.ts
- functional-test/pages/tabs/documents.ts
- functional-test/pages/tabs/history.ts
- functional-test/pages/tabs/summary.ts
- functional-test/playwright.config.ts
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> Sscssi 375

- Jenkinsfile_CNP
HLD pipeline has moved to sscs-tribunals-api
> Disable HLD on master
